NeosCommerce:
  Cart:
    templateRootPath: 'resource://NeosCommerce.Cart/Private/Templates/'
    linkToCart: '/warenkorb.html'
    linkToHome: '/'
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosCommerce.Cart:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        shop:
          position: 'end'
          label: 'Shop'
    fusion:
      autoInclude:
        NeosCommerce.Cart: true
  Flow:
    i18n:
      defaultLocale: de